version: '3.1'

services:
 postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432
    volumes:
    - ./db:/var/lib/postgresql/data