version: '3.1'

services:
 postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432
    volumes:
    - ./db:/var/lib/postgresql/data
 webapp:
    image: simo099/webapp:1.0.1
    depends_on:
      - postgres
    environment:
      - DB_URL=postgres://example:example@postgres/example
    ports:
      - 3000:3000